[Fixes]
ActorIsHostileToActor = true # Fixes a crash when invoking Actor.IsHostileToActor with a none form
CellInit = true              # Fixes a crash where a form does not get converted to a form pointer on unloaded cells
EncounterZoneReset = true    # Fixes encounter zones resetting immediately once you leave them on foot
FaderMenu = true             # Fixes a bug where the fader menu may not fully close
SafeExit = true              # Fixes crashes related to exiting the game that can be caused erroneously by F4SE plugin hooks
UnalignedLoad = true         # Fixes a crash related to SIMD intrinsics with an aligned move on unaligned memory
UtilityShader = true         # Fixes a crash when a shader can't be found for a given technique id

[Patches]
Achievements = true        # Enables achievements on modded saves
HavokMemorySystem = true   # Replaces the havok memory system with os allocators
MaxStdIO = -1              # Replaces the maximum stdio handles
MemoryManager = true       # Replaces the global memory manager with os allocators
MemoryManagerDebug = false # Enables debug tracing to determine faulting modules
ScaleformAllocator = true  # Replaces the scaleform memory allocator with os allocators
SmallBlockAllocator = true # Replaces the small block memory allocators with os allocators

[Warnings]
CreateTexture2D = true   # Warns when a call to CreateTexture2D fails
ImageSpaceAdapter = true # Warns on bad IMAD definitions which will corrupt your memory and crash your game

[Compatibility]
ClassicHolsteredWeapons = false # Patches Classic Holstered Weapons to be compatibile with the memory manager patch
F4EE = false                    # Patches F4EE to be compatibile with the memory manager patch
